name: shelf_virtual_directory
version: 2.0.0
description: >-
  This package provides a virtual directory to serve static files from a shelf
  server.
issue_tracker: https://github.com/RatakondalaArun/shelf_virtual_directory/issues
# author: Ratakondala Arun<arunratakondala3470@gmail.com>
repository: https://github.com/RatakondalaArun/shelf_virtual_directory.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mime: ^1.0.0
  path: ^1.8.0
  shelf: ^1.1.4
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^0.13.3
  lints: ^1.0.1
  test: ^1.17.9
