name: shelf_virtual_directory
version: 3.0.1
description: >-
  This package provides a virtual directory to serve static files from a shelf
  server.
issue_tracker: https://github.com/RatakondalaArun/shelf_virtual_directory/issues
# author: Ratakondala Arun<ratakondalaarun@gmail.com>
repository: https://github.com/RatakondalaArun/shelf_virtual_directory.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http_parser: ^4.0.0
  mime: ^1.0.1
  path: ^1.8.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2

dev_dependencies:
  http: ^0.13.4
  lints: ^1.0.1
  test: ^1.20.1
